# Generated by Django 6.1 on 2026-08-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('fields_to_watch', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('suggested_projects', models.JSONField(blank=True, default=list)),
                ('suggested_resources', models.JSONField(blank=True, default=list)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_stages', to='goals.career')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.roadmapstage')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='goals.skill')),
            ],
        ),
        migrations.AddField(
            model_name='roadmapstage',
            name='skills',
            field=models.ManyToManyField(blank=True, to='goals.skill'),
        ),
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(default='Beginner', max_length=30)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='goals.career')),
                ('develops_skills', models.ManyToManyField(related_name='project_developments', to='goals.skill')),
                ('required_skills', models.ManyToManyField(related_name='project_requirements', to='goals.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='goals.career')),
                ('skills', models.ManyToManyField(blank=True, to='goals.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_proficiency', models.PositiveSmallIntegerField(default=70)),
                ('importance', models.PositiveSmallIntegerField(default=50)),
                ('is_foundational', models.BooleanField(default=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='goals.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('career', 'skill'), name='unique_career_skill')],
            },
        ),
    ]
